my_port/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('port.urls', namespace='port'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
    document_root=settings.MEDIA_ROOT)

port/urls.py
from django.urls import path
from . import views

app_name = 'port'
urlpatterns = [
    path('', views.home, name='home'),
    path('<int:id>/<slug:slug>/', views.detail, name='detail'),
    path('about', views.about, name='about'),
    path('work', views.work, name='work'),
    path('contact', views.contact, name='contact'),
    path('term', views.term, name='term'),
    path('privacy', views.privacy, name='privacy'),
    path('cookies', views.cookies, name='cookies'),
    path('search', views.search, name='search'),
    path('download', views.download_resume, 'download'),

]

port/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Profile(models.Model):
    first_name =models.CharField(max_length=50)
    last_name =models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    phone = models.CharField(max_length=20, blank=True)
    age = models.PositiveIntegerField(blank=True)
    country = models.CharField(max_length=120, blank=True)
    city = models.CharField(max_length=120, blank=True)
    address = models.CharField(max_length=250, blank=True)
    zipcode = models.CharField(max_length=120, blank=True)
    photo = models.ImageField(upload_to='portfolio/%Y/%m/%d',blank=True)
    website = models.URLField(max_length=250, blank=True)
    github = models.URLField(max_length=250, null=True, blank=True)
    resume = models.FileField(upload_to='resume', null=True, blank=True)
    profession = models.CharField(max_length=100, null=True, blank=True)
    education = models.CharField(max_length=100, blank=True)
    experience = models.PositiveIntegerField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def get_absolute_url(self):
        return reverse("port:about", args=[self.id])

    def __str__(self):
        return self.first_name
    
    

class Portfolio(models.Model):
    creator = models.ForeignKey('Profile', on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=150)
    slug = models.SlugField(max_length=150)
    image = models.ImageField(upload_to='portfolio/%Y/%m/%d', blank=True)
    is_published = models.BooleanField(default=True, null=True)
    description = models.TextField(blank=True)
    website_link = models.URLField(max_length=250, blank=True)
    github_link = models.URLField(max_length=350, blank=True)
    skill = models.ManyToManyField('Skill', through='PortfolioSkill', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("port:detail", args=[self.id, self.slug])
    
    class Meta:
        ordering = ('-created_at',)
    
    def __str__(self):
        return self.name

class Skill(models.Model):
    name = models.CharField(max_length=120)
    rate = models.IntegerField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class PortfolioSkill(models.Model):
    portfolio = models.ForeignKey('Portfolio', on_delete=models.CASCADE,)
    skill = models.ForeignKey('Skill', on_delete=models.CASCADE)

    def __str__(self):
        return f'{ self.portfolio }, { self.skill }'

class Testimonial(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100, blank=True)
    body = models.TextField(null=True, blank=True)
    phone = models.CharField(max_length=20, blank=True)
    profession = models.CharField(max_length=100)
    image = models.ImageField(upload_to='testimonial/%Y/%m/%d', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.first_name
    

class Contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    subject = models.CharField(max_length=250, blank=True)
    message = models.TextField(blank=True)

port/forms.py
from django import forms
from django.forms import ModelForm
from .models import Contact

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control'}),
            'email': forms.TextInput(attrs={'class':'form-control'}),
            'subject': forms.TextInput(attrs={'class':'form-control'}),
            'message': forms.Textarea(attrs={'class':'form-control'}),
            }

port/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Profile, Portfolio, Skill, Testimonial, PortfolioSkill, Contact
from .forms import ContactForm
from django.core.mail import send_mail

# Create your views here.
def home(request):
    portfolios = Portfolio.objects.filter(is_published=True)
    testimonial1 = Testimonial.objects.get(id=1)
    testimonial2 = Testimonial.objects.get(id=2)
    skills = Skill.objects.all()
    profile = Profile.objects.get(id=1)
    form = ContactForm()
        
    return render(request, 'port/home.html', {
        'portfolios':portfolios,
        'testimonial1':testimonial1,
        'testimonial2':testimonial2,
        'skills': skills,
        'profile': profile,
        'form': form,
    })

def detail(request, id, slug):
    portfolio = get_object_or_404(Portfolio, id=id, slug=slug)
    skills = portfolio.skill.all()
    return render(request, 'port/detail.html', {'portfolio': portfolio, 'skills': skills})

def about(request):
    profile = Profile.objects.get(id=1)
    skills = Skill.objects.all()
    return render(request, 'port/about.html', {'profile': profile, 'skills': skills})

def work(request):
    portfolios = Portfolio.objects.filter(is_published=True)

    return render(request, 'port/work.html', {'portfolios' :portfolios})

def contact(request):
    profile = Profile.objects.get(id=1)
    submitted = False
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            send_mail(
                cd['subject'],
                cd['message'],
                cd.get('email', 'noreply@example.com'),
                ['helloworld@gmail.com'],
            )
            form.save()
            submitted=True
    else:
        form = ContactForm()
        if 'submitted' in request.GET:
            submitted = True
    return render(request, 'port/contact.html', {'form': form, 'submitted': submitted, 'profile': profile})

def term(request):
    return render(request, 'port/term.html')

def privacy(request):
    return render(request, 'port/privacy.html')

def cookies(request):
    return render(request, 'port/cookies.html')


def search(request):
    if request.method == 'POST':
        searched = request.POST['searched']
        portfolio_lists = Portfolio.objects.filter(is_published=True)
        results = portfolio_lists.filter(name__icontains=searched)
        return render(request, 'port/search.html', {'searched': searched, 'results': results})
    return render(request, 'port/search.html')

def download_resume(request, path):
    file_path = os.path.join(settings.MEDIA_ROOT, path)
    if os.path.exists(file_path):
        with open(file_path, 'rb') as fh:
            response = HttpResponse(fh.read(), content_type='resume')
            response['Content-Disposition']='inline;filename='+os.path.basename(file_path)
            return response
    raise Http404

port/templates/base.html
{% load static %}
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <!-- bootstrap -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <!-- css -->
  <link rel="stylesheet" href="{% static 'main.css' %}">
  <title>{% block title %}{% endblock %}</title>
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'port:home' %}"><img src="{% static 'img/logo3.png' %}" alt="" style="width:30%;"></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link  fs-5 text-light px-5 active" aria-current="page" href="{% url 'port:home' %}">HOME</a>
          </li>
          <li class="nav-item">
            <a class="nav-link fs-5 text-light px-5 " href="{% url 'port:about' %}">ABOUT</a>
          </li>
          <li class="nav-item">
            <a class="nav-link fs-5 text-light px-5 " href="{% url 'port:contact' %}">CONTACT</a>
          </li>
          <li class="nav-item">
            <a class="nav-link fs-5 text-light px-5 " href="{% url 'port:work' %}">WORK</a>
          </li>
         
        </ul>
        <form action="{% url 'port:search' %}" method="post" class="d-flex fs-5 my-2">
          {% csrf_token %}
          <input class="form-control me-2" type="search" name="searched" placeholder="SEARCH"
          aria-label="Search">
          <button class="btn btn-outline-danger" type="submit">SEARCH</button>
        </form>
      </div>
    </div>
  </nav>

  {% block content %}
  {% endblock %}
  <!-- ======= Footer ======= -->
  <footer>
    <div class="container-fluid">
      <div class="row text-center">
        <div class="col p-5">
          <p> <a href="{% url 'port:about' %}" class="nav-link footer-link text-white">About Me</a> </p>
          <p> <a href="{% url 'port:contact' %}" class="nav-link footer-link text-white">Contact Me</a> </p>

        </div>
        <div class="col p-5">
          <p> <a href="{% url 'port:term' %}" class="nav-link footer-link text-white">Terms</a></p>
          <p> <a href="{% url 'port:privacy' %}" class="nav-link footer-link text-white">Privacy Policy</a></p>

        </div>
        <div class="col p-5">
          <p> <a href="{% url 'port:cookies' %}" class="nav-link footer-link text-white">Cookie Settings</a> </p>
          <p> <a href="{% url 'port:work' %}" class="nav-link footer-link text-white">Feautured Projects</a></p>
        </div>
      </div>
    </div>
  </footer><!-- End  Footer -->

  <!-- bootstrap javascript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <!-- javascript -->
  <script src="{% static 'script.js' %}"></script>
</body>

</html>

port/templates/port/home.html
{% extends 'base.html' %}
{% load static %}
{% block title %}home{% endblock %}
{% block content %}
<!-- banner -->

<div class="container-fluid" id="banner-section">
    <div class="banner-header">
        <h1 class="display-1 fw-bolder">
            I AM EPHREM
        </h1>
    </div>
    <div class="banner text">
        <h4 class="display-6 fw-bolder">
            Full stack developer
        </h4>
    </div>
    <div class="banner-button my-3">
        <a href="{% url 'port:contact' %}"><button type="button" class="btn btn-primary btn-lg m-2 px-5 py-2 fw-bolder">Contact</button></a>
        <a href="{{ profile.resume.url }}" download="{{ profile.resume.url }}"><button type="button" class="btn btn-outline-danger btn-lg m-2 px-3 py-2 fw-bolder">Download Resume</button></a>
    </div>
</div>
<!-- main -->
<div class="container main-section my-4">
    <!-- main-header -->
    <div class="header">
        <h1 class="display-2 fw-bolder text-center my-5">
            MY WORK
        </h1>
    </div>
    <!-- main-detail -->
    <div class="row row-cols-1 row-cols-md-2 g-4">
        {% for portfolio in portfolios %}
        <div class="col">
            <div class="card">
                <a href="{{ portfolio.get_absolute_url }}"><img src="{{ portfolio.image.url }}" class="card-img-top" alt="..."></a>
                <div class="card-body">
                    <a class="nav-link fs-5 px-0 text-center" href="{{ portfolio.get_absolute_url }}"><h5 class="card-title">{{ portfolio.name }}</h5></a> 
                    <ul class="text-center">
                        <a href="{{ portfolio.github_link }}" class="nav-link d-inline fs-2 px-5"><li class="nav-item d-inline"><svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                            <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.012 8.012 0 0 0 16 8c0-4.42-3.58-8-8-8z"/>
                          </svg></i></li></a>
                        <a href="{{ portfolio.website_link }}" class="nav-link d-inline fs-2 px-5"><li class="nav-item d-inline"><svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-globe" viewBox="0 0 16 16">
                            <path d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8zm7.5-6.923c-.67.204-1.335.82-1.887 1.855A7.97 7.97 0 0 0 5.145 4H7.5V1.077zM4.09 4a9.267 9.267 0 0 1 .64-1.539 6.7 6.7 0 0 1 .597-.933A7.025 7.025 0 0 0 2.255 4H4.09zm-.582 3.5c.03-.877.138-1.718.312-2.5H1.674a6.958 6.958 0 0 0-.656 2.5h2.49zM4.847 5a12.5 12.5 0 0 0-.338 2.5H7.5V5H4.847zM8.5 5v2.5h2.99a12.495 12.495 0 0 0-.337-2.5H8.5zM4.51 8.5a12.5 12.5 0 0 0 .337 2.5H7.5V8.5H4.51zm3.99 0V11h2.653c.187-.765.306-1.608.338-2.5H8.5zM5.145 12c.138.386.295.744.468 1.068.552 1.035 1.218 1.65 1.887 1.855V12H5.145zm.182 2.472a6.696 6.696 0 0 1-.597-.933A9.268 9.268 0 0 1 4.09 12H2.255a7.024 7.024 0 0 0 3.072 2.472zM3.82 11a13.652 13.652 0 0 1-.312-2.5h-2.49c.062.89.291 1.733.656 2.5H3.82zm6.853 3.472A7.024 7.024 0 0 0 13.745 12H11.91a9.27 9.27 0 0 1-.64 1.539 6.688 6.688 0 0 1-.597.933zM8.5 12v2.923c.67-.204 1.335-.82 1.887-1.855.173-.324.33-.682.468-1.068H8.5zm3.68-1h2.146c.365-.767.594-1.61.656-2.5h-2.49a13.65 13.65 0 0 1-.312 2.5zm2.802-3.5a6.959 6.959 0 0 0-.656-2.5H12.18c.174.782.282 1.623.312 2.5h2.49zM11.27 2.461c.247.464.462.98.64 1.539h1.835a7.024 7.024 0 0 0-3.072-2.472c.218.284.418.598.597.933zM10.855 4a7.966 7.966 0 0 0-.468-1.068C9.835 1.897 9.17 1.282 8.5 1.077V4h2.355z"/>
                          </svg></i></li></a>
                        <a href="{{ portfolio.get_absolute_url }}" class="nav-link d-inline fs-2 px-5"><li class="nav-item d-inline"><svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-plus-circle-fill" viewBox="0 0 16 16">
                            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v3h-3a.5.5 0 0 0 0 1h3v3a.5.5 0 0 0 1 0v-3h3a.5.5 0 0 0 0-1h-3v-3z"/>
                          </svg></i></li></a> 
                    </ul>
                </div>
            </div>
        </div>
        {% empty %}
        <h3>No portfolio at this time </h3>
        {% endfor %}
    </div>
</div>

<!-- about -->
<div class="container my-4">
    <div class="header">
        <h1 class="display-2 fw-bolder text-center my-5">
            ABOUT
        </h1>
    </div>
</div>

<div class="container">
    <div class="row my-3">
        <div class="col-lg-7 col-md-12 col-sm-12 py-3">
            <img class="rounded float-start" src="{% static 'img/profile1.jpg' %}" alt="" style="max-width: 80% ;">
        </div>
        <div class="col-lg-5 col-md-12 col-sm-12">
            <div class="about-info text-center-justify my-3 py-5">
                <p class="fs-5 fw-bolder"><span>Name: </span> <span>{{ profile.first_name }}
                        {{ profile.last_name }}</span></p>
                <p class="fs-5 fw-bolder"><span>Profile: </span> <span>{{ profile.profession }}</span></p>
                <p class="fs-5 fw-bolder"><span>Email: </span> <span>{{ profile.email}}</span></p>
                <p class="fs-5 fw-bolder"><span>Phone: </span> <span>{{ profile.phone}}</span></p>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6 col-md-5">
            <h3 class="my-3">Skill</h3>
            <div class="mb-2">
                {% for skill in skills %}
                <span>{{ skill.name|upper }}</span>
                <div class="progress">
                    <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar"
                        style="width: {{ skill.rate }}%;" aria-valuenow="{{ skill.rate }}" aria-valuemin="0"
                        aria-valuemax="100">{{ skill.rate }}</div>
                </div>
                {% empty %}
                <p>No skill listed here</p>
                {% endfor %}
            </div>
        </div>
        <div class="col-lg-6 col-md-7">
            <div class="about-me pt-4 pt-md-0">
                <p class="lead">
                    Curabitur non nulla sit amet nisl tempus convallis quis ac lectus. Curabitur
                    arcu erat, accumsan id
                    imperdiet et, porttitor
                    at sem. Praesent sapien massa, convallis a pellentesque nec, egestas non nisi.
                    Nulla
                    porttitor accumsan tincidunt.
                </p>
                <p class="lead">
                    Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a. Vivamus suscipit
                    tortor eget felis
                    porttitor volutpat. Vestibulum
                    ac diam sit amet quam vehicula elementum sed sit amet dui. porttitor at sem.
                </p>
                <p class="lead">
                    Nulla porttitor accumsan tincidunt. Quisque velit nisi, pretium ut lacinia in,
                    elementum id enim.
                    Nulla porttitor accumsan
                    tincidunt. Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a.
                </p>
            </div>
        </div>

    </div>
</div>

<!-- counter -->

<div class="container">
    <h1 class="display-3 fw-bolder text-center my-5">
        EXPERIENCE
    </h1>
</div>
<div class="container-fluid" id="counter-section">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-lg-6 fw-bolder">
                <p class="py-3 fs-4">{{ portfolios|length }}</p>
                <p class="lead fs-4 fw-bolder">
                    WORKS COMPLETED
                </p>

            </div>
            <div class="col-sm-3 col-lg-3">
                <p class="py-3 fs-4">{{ profile.experience }}</p>
                <p class="lead fs-4 fw-bolder">
                    YEARS OF EXPERIENCE
                </p>

            </div>
        </div>
    </div>
</div>
<!-- End Counter Section -->

<!-- testimonial -->
<div class="container">
    <h1 class="display-3 fw-bolder text-center my-5">
        TESTIMONIALS
    </h1>
</div>
<div id="carouselExampleDark" class="carousel carousel-light slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active"
            aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active" data-bs-interval="10000" style="background-color:rgb(0, 5, 12); height:30rem;">
            <div class="carousel-caption d-md-block text-white" style="position: absolute; bottom: 100px;">
                <img src="{{ testimonial1.image.url }}" class="w-20" alt="..." style="width: 16rem; border-radius:50%">
                <h5 class="fs-5">{{ testimonial1.first_name }}</h5>
                <p class="lead">{{ testimonial1.body }}</p>
            </div>
        </div>
        <div class="carousel-item" data-bs-interval="2000" style="background-color:rgb(0, 2, 5); height:30rem; ">
            <div class="carousel-caption d-md-block text-white" style="position: absolute; bottom: 100px;">
                <img src="{{ testimonial2.image.url }}" class="w-20" alt="..." style="width: 16rem; border-radius:50%">
                <h5 class="fs-5">{{ testimonial2.first_name }}</h5>
                <p class="lead">{{ testimonial2.body }}</p>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<!-- End Testimonials Section -->
<!-- contact -->
<div class="container">
    <h1 class="display-3 fw-bolder my-5 text-center">
        CONTACT ME
    </h1>
</div>
<div class="container-fluid" id="contact-section">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-6">
                <form action="{% url 'port:contact' %}" method="post" class="text-light fw-bolder fs-6 text-uppercase">
                    <div class="row">
                        <div class="col-md-12 mb-3">
                            <div class="form-group text-start">
                                {{ form.as_p }}
                                <div class="col-md-12 text-center">
                                    <button type="submit" class="btn btn-primary btn-lg m-3 px-4 py-2 fw-bolder">Send
                                        Message</button>
                                </div>
                                {% csrf_token %}
                            </div>
                        </div>

                    </div>
                </form>
            </div>

            <div class="col-sm-12 col-md-6">
                <div class="pt-4 pt-md-0">
                    <h5 class="">
                        Get in Touch
                    </h5>
                </div>
                <div class="more-info">
                    <p class="lead text-start">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit. Facilis dolorum
                        dolorem soluta quidem
                        expedita aperiam aliquid at.
                        Totam magni ipsum suscipit amet? Autem nemo esse laboriosam ratione nobis
                        mollitia inventore?
                    </p>
                    <div class="container col-sm-11 col-md-11 col-lg-10 p-3"></div>
                    <div class="mb-2 text-light text-start">
                        <div class="d-inline pr-5"></div>
                        <div class="d-inline p-2 fs-5">{{ profile.address }}</div>
                    </div>
                    <div class="mb-2 text-light text-start =">
                        <div class="d-inline pr-5"></div>
                        <div class="d-inline p-2 fs-5">{{ profile.phone }}</div>
                    </div>
                    <div class="mb-2 text-light text-start">
                        <div class="d-inline pr-5"></div>
                        <div class="d-inline p-2 fs-5">{{ profile.website }}</div>
                    </div>

                    <div class="socials text-start">
                        <ul class="list-inline">
                            <li class="list-inline-item px-3"><a class="nav-link" href="{{ profile.website }}"></a></li>
                            <li class="list-inline-item px-3"><a class="nav-link" href="{{ profile.github }}"></a>
                            </li>
                            <li class="list-inline-item px-3"><a class="nav-link" href=""></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- End Contact Section -->



{% endblock %}

port/templates/port/search.html
{% extends 'base.html' %}
{% load static %}

{% block title %}search{% endblock %}

{% block content %}

<!-- ======= Cookies ======= -->
<div class="container-fluid" id="search-section" style="height: 700px;">
    <div class="container">
        <h1 class="display-3 fw-bolder mb-4 text-center" id="main-header">
            SEARCH
        </h1>
    </div>
    {% if searched %}
    <div class="container py-2">
        <div class="row">
            <h3 class="text-light bg-primary p-2">Portfolio that contains <em>"{{ searched }}"</em> </h3>
            <div class="col py-3 px-6">
                {% for result in results %}
                <h4 class="text-light fw-bolder text-center"><a class="nav-link p-2" href="{{ result.get_absolute_url }}">{{ result.name }}</a></h4>
                {% empty %}
                <h4 class="text-light fw-bolder">{{ searched}} not found</h4>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endif %}
</div>

{% endblock %}